### ISSUE TITLE
Simple build script not working

### ISSUE THREAD

**Issue by dirkluijk** [elfet/deployer#133]
Hi,

I have a quite simple build script. It just performs a ``git pull`` and runs some other scripts afterwards. My ``deploy.php``:

```php
server('myserver', '****', 22)
    ->path('~/public_html')
    ->user('someuser');

/**
 * Update project code
 */
task('deploy:update_code', function () {
    run("git reset --hard");
    run("git pull origin master");
})->desc('Updating code');

/**
 * Update project dependencies
 */
task('deploy:update_dependencies', function () {
    writeln("Updating npm libraries...");
    run("npm update");

    writeln("Updating bower packages...");
    run("bower update");
})->desc('Updating dependencies');

/**
 * Running gulp
 */
task('deploy:gulp', function () {
    writeln("Compiling LESS sources...");
    run("./node_modules/.bin/gulp");
})->desc("Running gulp");

task('deploy', [
    'deploy:update_code',
    'deploy:update_dependencies',
    'deploy:gulp'
]);
```

When I run ``dep deploy -vvv`` I get:

```
Updating code
Run task deploy:update_code on server myserver
[***] cd ~/public_html && git reset --hard
Password: 
[***] :: 
[***] cd ~/public_html && git pull origin master
[***] :: 
✔
Updating dependencies
Run task deploy:update_dependencies on server myserver
Updating npm libraries...
[***] cd ~/public_html && npm update
[***] :: 
Updating bower packages...
[***] cd ~/public_html && bower update
[***] :: 
✔
Running gulp
Run task deploy:gulp on server myserver
Compiling LESS sources...
[***] cd ~/public_html && ./node_modules/.bin/gulp
[***] :: 
✔
```

The git repo is not updated. However, manually entering the commands via SSH does work. Any ideas?

**Comment by elfet** [comment]
Try to login on server with same user as in `deploy.php` and run `git pull origin master`.
Also now what now deployer does not support ssh agent forwarding, so you need manually add your server keys to git repository.

**Comment by dirkluijk** [comment]
I have the contents of ``~/.ssh/id_rsa.pub`` already added ad deployment key to my repository (Bitbucket), is that what you mean?

``git pull origin master`` works only when I execute it manually.

**Comment by elfet** [comment]
Do you execute it manually on you remote servers?

**Comment by dirkluijk** [comment]
Yes. It seems the ``pull`` does work, although there is an error (still not sure why).

```
[myuser@myserver public_html]$ cd ~/public_html && git pull origin master
remote: Counting objects: 3, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 2), reused 0 (delta 0)
Unpacking objects: 100% (3/3), done.
From bitbucket.org:my/repository
 * branch            master     -> FETCH_HEAD
Updating 76480be..510f4e0
Fast-forward
 index.html |    1 +
 1 files changed, 1 insertions(+), 0 deletions(-)
Error: spawn EACCES
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)
```
I don't see how this error could possibly block Deployer, so it might have nothing to do with it.

**Comment by elfet** [comment]
Hmmm, try to solve this error first.

**Comment by dirkluijk** [comment]
I removed the error by removing my working copy and cloning it again... but the problem still occurs.

**Comment by elfet** [comment]
Cant say why. Need more information about.

**Comment by dirkluijk** [comment]
It looks like it's an SSH issue, after debugging I found that the commands are not executed.

In phpseclib/Net/SSH2.php, on line 2272:

```
    function exec($command, $callback = null)
    {
        // ...

        if (!($this->bitmap & NET_SSH2_MASK_LOGIN)) {
            return false; // returns false
        }
        
        // ...
    }
```

**Comment by elfet** [comment]
Yeah. It's bug in PhpSecLib. :(

You can enable PHP extension ssh2 and everything will be working smoothly.

**Comment by dirkluijk** [comment]
Yeah, I will try that. Thanks!
